// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFC4wAcQNZVYmW5kOrFK6_5kxTiwHq9-k',
    appId: '1:209435659853:web:4bfe046d678b0299449604',
    messagingSenderId: '209435659853',
    projectId: 'skillsync-ai-a8f8b',
    authDomain: 'skillsync-ai-a8f8b.firebaseapp.com',
    storageBucket: 'skillsync-ai-a8f8b.firebasestorage.app',
    measurementId: 'G-719ELCMX9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6R1WcNRuu9edlxUXTdRMDEcJCLeTNfs',
    appId: '1:209435659853:android:ba99de82dd4910fa449604',
    messagingSenderId: '209435659853',
    projectId: 'skillsync-ai-a8f8b',
    storageBucket: 'skillsync-ai-a8f8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX-1-cWcaTgQFNKzrg5GLmog55oa-OFo',
    appId: '1:209435659853:ios:42de5724bf890718449604',
    messagingSenderId: '209435659853',
    projectId: 'skillsync-ai-a8f8b',
    storageBucket: 'skillsync-ai-a8f8b.firebasestorage.app',
    iosBundleId: 'com.example.skillsyncAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlX-1-cWcaTgQFNKzrg5GLmog55oa-OFo',
    appId: '1:209435659853:ios:42de5724bf890718449604',
    messagingSenderId: '209435659853',
    projectId: 'skillsync-ai-a8f8b',
    storageBucket: 'skillsync-ai-a8f8b.firebasestorage.app',
    iosBundleId: 'com.example.skillsyncAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFC4wAcQNZVYmW5kOrFK6_5kxTiwHq9-k',
    appId: '1:209435659853:web:a1aad8d500cbccce449604',
    messagingSenderId: '209435659853',
    projectId: 'skillsync-ai-a8f8b',
    authDomain: 'skillsync-ai-a8f8b.firebaseapp.com',
    storageBucket: 'skillsync-ai-a8f8b.firebasestorage.app',
    measurementId: 'G-QJRR6TVVDY',
  );
}
